apiVersion: 1
datasources:
  - name: OpenSearch
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    isDefault: true
    jsonData:
      database: "otel-logs"
      flavor: opensearch
      version: "2.17.0"
      timeField: "@timestamp"
      logMessageField: body
      logLevelField: severity_text

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
