apiVersion: 1

policies:
  - orgId: 1
    receiver: discord
    group_by:
      - alertname
      - project
    group_wait: 30s
    # group_interval : délai avant d'émettre une mise à jour du groupe
    # (notamment le RESOLVED). Court pour des notifs de récupération rapides.
    group_interval: 1m
    repeat_interval: 4h
    routes:
      # Les alertes "critical" repartent plus vite
      - receiver: discord
        matchers:
          - severity = critical
        group_wait: 10s
        group_interval: 30s
        repeat_interval: 1h
