apiVersion: 1

policies:
  - orgId: 1
    receiver: discord
    group_by:
      - alertname
      - project
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      # Les alertes "critical" repartent plus vite
      - receiver: discord
        matchers:
          - severity = critical
        group_wait: 10s
        repeat_interval: 1h
