apiVersion: 1

templates:
  - orgId: 1
    name: discord-templates
    template: |
      {{ define "discord.title" }}{{ if eq .Status "firing" }}🔴 [FIRING]{{ else }}✅ [RESOLVED]{{ end }} {{ .CommonLabels.alertname }}{{ end }}

      {{ define "discord.message" }}
      {{ if gt (len .Alerts.Firing) 0 }}**🔴 {{ len .Alerts.Firing }} alerte(s) active(s)**
      {{ range .Alerts.Firing }}
      • {{ .Annotations.summary }}
        {{ range .Labels.SortedPairs }}{{ if or (eq .Name "project") (eq .Name "service_name") (eq .Name "severity") }}`{{ .Name }}={{ .Value }}` {{ end }}{{ end }}
      {{ end }}{{ end }}
      {{ if gt (len .Alerts.Resolved) 0 }}**✅ {{ len .Alerts.Resolved }} alerte(s) résolue(s)**
      {{ range .Alerts.Resolved }}
      • {{ .Annotations.summary }}
      {{ end }}{{ end }}
      {{ end }}
